/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AgendarCitasAPP.view;

import AgendarCitasAPP.Controllers.AdminController;
import AgendarCitasAPP.Dominio.Entidades.Usuario;
import AgendarCitasAPP.Dominio.Utils.JsonUtils;
import AgendarCitasAPP.view.EditarUsuarioFrame;
import com.google.gson.reflect.TypeToken;
import java.awt.event.ActionEvent;
import java.io.IOException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sebastian JB
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
         initComponents(); // Pasar el modelo de la tabla al controlador
    try {
        AdminController.cargarPacientesEnTabla(
            (DefaultTableModel) tablaUsuarios.getModel() // ← Aquí sí usas tablaUsuarios
        );
    } catch (RuntimeException e) {
        JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }
    
    
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        TabPaneReportes = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        PanelGestionMedicos = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        PanelGestionUsuarios = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PanelGestionCitas1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        TabPaneAdmin = new javax.swing.JTabbedPane();
        paneGestionUsuario = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        BtnEditarUsuarioAdmin = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        paneGestionMedicos = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        paneGestionCitas = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        paneReportes = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(49, 82, 192));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 694, -1, -1));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 728, -1, -1));

        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 768, -1, -1));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 790, 58, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TabPaneReportes.setBackground(new java.awt.Color(255, 255, 102));
        TabPaneReportes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TabPaneReportes.setFocusable(false);
        TabPaneReportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabPaneReportesMouseClicked(evt);
            }
        });
        TabPaneReportes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Reportes");
        TabPaneReportes.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel3.add(TabPaneReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 130, 40));

        PanelGestionMedicos.setBackground(new java.awt.Color(255, 204, 204));
        PanelGestionMedicos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelGestionMedicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelGestionMedicosMouseClicked(evt);
            }
        });
        PanelGestionMedicos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("Gestión de médicos");
        PanelGestionMedicos.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 10, 120, -1));

        jPanel3.add(PanelGestionMedicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 140, 40));

        PanelGestionUsuarios.setBackground(new java.awt.Color(204, 204, 255));
        PanelGestionUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelGestionUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelGestionUsuariosMouseClicked(evt);
            }
        });
        PanelGestionUsuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText(" Gestión de usuarios");
        PanelGestionUsuarios.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel3.add(PanelGestionUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 130, 40));

        PanelGestionCitas1.setBackground(new java.awt.Color(204, 255, 204));
        PanelGestionCitas1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelGestionCitas1.setFocusable(false);
        PanelGestionCitas1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PanelGestionCitas1MouseClicked(evt);
            }
        });
        PanelGestionCitas1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setText("Gestión de citas");
        PanelGestionCitas1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel3.add(PanelGestionCitas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 130, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 40));

        jPanel6.setBackground(new java.awt.Color(204, 255, 204));
        jPanel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel6.setFocusable(false);
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("Gestión de citas");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 130, 40));

        paneGestionUsuario.setBackground(new java.awt.Color(204, 204, 255));

        jScrollPane1.setBackground(new java.awt.Color(204, 204, 255));

        jPanel11.setBackground(new java.awt.Color(204, 204, 255));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Apellido", "Clave", "Fecha Nacimiento", "Direccion", "tellefono", "Correo"
            }
        ));
        jScrollPane2.setViewportView(tablaUsuarios);

        jPanel11.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 320));

        jLabel9.setText("jLabel9");
        jPanel11.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, -1, -1));

        BtnEditarUsuarioAdmin.setText("Editar");
        BtnEditarUsuarioAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarUsuarioAdminActionPerformed(evt);
            }
        });
        jPanel11.add(BtnEditarUsuarioAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel11.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, -1, -1));

        jScrollPane1.setViewportView(jPanel11);

        javax.swing.GroupLayout paneGestionUsuarioLayout = new javax.swing.GroupLayout(paneGestionUsuario);
        paneGestionUsuario.setLayout(paneGestionUsuarioLayout);
        paneGestionUsuarioLayout.setHorizontalGroup(
            paneGestionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        paneGestionUsuarioLayout.setVerticalGroup(
            paneGestionUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        TabPaneAdmin.addTab("0", paneGestionUsuario);

        paneGestionMedicos.setBackground(new java.awt.Color(255, 204, 204));
        paneGestionMedicos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(255, 204, 204));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Especialidad", "Email", "Disponibilidad"
            }
        ));
        jScrollPane5.setViewportView(jTable3);

        jPanel10.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 328));

        jScrollPane3.setViewportView(jPanel10);

        paneGestionMedicos.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, -2, 800, 360));

        TabPaneAdmin.addTab("1", paneGestionMedicos);

        paneGestionCitas.setBackground(new java.awt.Color(204, 255, 204));
        paneGestionCitas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Paciente", "Medico", "Fecha", "Hora", "Estado"
            }
        ));
        jScrollPane6.setViewportView(jTable4);

        paneGestionCitas.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 328));

        TabPaneAdmin.addTab("2", paneGestionCitas);

        paneReportes.setBackground(new java.awt.Color(255, 255, 102));

        javax.swing.GroupLayout paneReportesLayout = new javax.swing.GroupLayout(paneReportes);
        paneReportes.setLayout(paneReportesLayout);
        paneReportesLayout.setHorizontalGroup(
            paneReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        paneReportesLayout.setVerticalGroup(
            paneReportesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 355, Short.MAX_VALUE)
        );

        TabPaneAdmin.addTab("3", paneReportes);

        jPanel1.add(TabPaneAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 800, 390));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 800, 430));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Planifica+");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TabPaneReportesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabPaneReportesMouseClicked
        TabPaneAdmin.setSelectedIndex(3);   // TODO add your handling code here:
    }//GEN-LAST:event_TabPaneReportesMouseClicked

    private void PanelGestionMedicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelGestionMedicosMouseClicked
        TabPaneAdmin.setSelectedIndex(1);   // TODO add your handling code here:
    }//GEN-LAST:event_PanelGestionMedicosMouseClicked

    private void PanelGestionUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelGestionUsuariosMouseClicked
        TabPaneAdmin.setSelectedIndex(0);
    }//GEN-LAST:event_PanelGestionUsuariosMouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        
    }//GEN-LAST:event_jPanel6MouseClicked

    private void PanelGestionCitas1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PanelGestionCitas1MouseClicked
       TabPaneAdmin.setSelectedIndex(2);
    }//GEN-LAST:event_PanelGestionCitas1MouseClicked

    private void BtnEditarUsuarioAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarUsuarioAdminActionPerformed
        int filaSeleccionada = tablaUsuarios.getSelectedRow();
    
    if (filaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, 
            "Por favor seleccione un usuario de la tabla para editar", 
            "Advertencia", 
            JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    try {
        // Obtener los datos de la fila seleccionada
        String id = tablaUsuarios.getValueAt(filaSeleccionada, 0).toString();
        String nombre = tablaUsuarios.getValueAt(filaSeleccionada, 1).toString();
        String apellido = tablaUsuarios.getValueAt(filaSeleccionada, 2).toString();
        String clave = tablaUsuarios.getValueAt(filaSeleccionada, 3).toString();
        String fechaNacimiento = tablaUsuarios.getValueAt(filaSeleccionada, 4).toString();
        String direccion = tablaUsuarios.getValueAt(filaSeleccionada, 5).toString();
        String telefono = tablaUsuarios.getValueAt(filaSeleccionada, 6).toString();
        String correo = tablaUsuarios.getValueAt(filaSeleccionada, 7).toString();
        
        // Crear y mostrar el frame de edición
        EditarUsuarioFrame editarFrame = new EditarUsuarioFrame(
            id, nombre, apellido, clave, fechaNacimiento, direccion, 
            telefono, correo, (DefaultTableModel) tablaUsuarios.getModel()
        );
        editarFrame.setVisible(true);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, 
            "Error al obtener datos del usuario: " + e.getMessage(), 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_BtnEditarUsuarioAdminActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
       btnEliminar.addActionListener(e -> {
    int filaSeleccionada = tablaUsuarios.getSelectedRow();
    if (filaSeleccionada == -1) {
        JOptionPane.showMessageDialog(this, 
            "Seleccione un usuario para eliminar", 
            "Advertencia", 
            JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    String id = tablaUsuarios.getValueAt(filaSeleccionada, 0).toString();
    
    try {
        // Confirmación antes de eliminar
        int confirmacion = JOptionPane.showConfirmDialog(
            this, 
            "¿Está seguro de eliminar este usuario?", 
            "Confirmar eliminación",
            JOptionPane.YES_NO_OPTION);
        
        if (confirmacion == JOptionPane.YES_OPTION) {
            AdminController.eliminarUsuario(id, (DefaultTableModel) tablaUsuarios.getModel());
            JOptionPane.showMessageDialog(this, 
                "Usuario eliminado correctamente", 
                "Éxito", 
                JOptionPane.INFORMATION_MESSAGE);
        }
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, 
            "Error al eliminar usuario: " + ex.getMessage(), 
            "Error", 
            JOptionPane.ERROR_MESSAGE);
    }
});
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEditarUsuarioAdmin;
    private javax.swing.JPanel PanelGestionCitas1;
    private javax.swing.JPanel PanelGestionMedicos;
    private javax.swing.JPanel PanelGestionUsuarios;
    private javax.swing.JTabbedPane TabPaneAdmin;
    private javax.swing.JPanel TabPaneReportes;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JPanel paneGestionCitas;
    private javax.swing.JPanel paneGestionMedicos;
    private javax.swing.JPanel paneGestionUsuario;
    private javax.swing.JPanel paneReportes;
    private javax.swing.JTable tablaUsuarios;
    // End of variables declaration//GEN-END:variables
}
