/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AgendarCitasAPP.view;

import AgendarCitasAPP.Controllers.AdminController;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sebas
 */
public class EditarUsuarioFrame extends javax.swing.JFrame {

    /**
     * Creates new form EditarUsuarioFrame
     */
    private DefaultTableModel modeloTabla; // Añade esta línea

    public EditarUsuarioFrame(String id, String nombre, String apellido, String clave, 
        String fechaNacimiento, String direccion, String telefono, String correo,
        DefaultTableModel modeloTabla) {
        initComponents();
        
        this.modeloTabla = modeloTabla;
        
        // Establecer valores en los campos
        txtId.setText(id);
        txtNombre.setText(nombre);
        txtApellido.setText(apellido);
        txtClave.setText(clave);
        txtFechaNacimiento.setText(fechaNacimiento);
        txtDireccion.setText(direccion);
        txtTele.setText(telefono);
        txtCorreo.setText(correo);
        
        // Limpiar textos por defecto incorrectos
        txtId.setForeground(java.awt.Color.BLACK);
        txtNombre.setForeground(java.awt.Color.BLACK);
        txtApellido.setForeground(java.awt.Color.BLACK);
        txtClave.setForeground(java.awt.Color.BLACK);
        txtFechaNacimiento.setForeground(java.awt.Color.BLACK);
        txtDireccion.setForeground(java.awt.Color.BLACK);
        txtTele.setForeground(java.awt.Color.BLACK);
        txtCorreo.setForeground(java.awt.Color.BLACK);
        
        // Configurar botón cancelar
        BtnCancelar.addActionListener(e -> this.dispose());
        
        // Configurar botón guardar
        BtnEditar.addActionListener(e -> guardarCambios());
    }
    
   private void guardarCambios() {
        try {
            // Obtener los nuevos valores
            String id = txtId.getText();
            String nombre = txtNombre.getText();
            String apellido = txtApellido.getText();
            String clave = txtClave.getText();
            String fechaNacimiento = txtFechaNacimiento.getText();
            String direccion = txtDireccion.getText();
            String telefono = txtTele.getText();
            String correo = txtCorreo.getText();
            String rol = cmbRol.getSelectedItem().toString();
            String genero = cmbGenero.getSelectedItem().toString();
            
            // Validación básica de campos
            if (nombre.isEmpty() || apellido.isEmpty() || clave.isEmpty() || 
                fechaNacimiento.isEmpty() || direccion.isEmpty() || 
                telefono.isEmpty() || correo.isEmpty()) {
                throw new Exception("Todos los campos son obligatorios");
            }
            
            // Validación de correo electrónico
            if (!correo.contains("@") || !correo.contains(".")) {
                throw new Exception("El correo electrónico no es válido");
            }
            
            // Actualizar en la base de datos
            AdminController.actualizarUsuario(
                id, nombre, apellido, clave, fechaNacimiento, 
                direccion, telefono, correo, genero, rol
            );
            
            // Actualizar la tabla en Admin
            AdminController.cargarPacientesEnTabla(modeloTabla);
            
            JOptionPane.showMessageDialog(this, 
                "Usuario actualizado correctamente", 
                "Éxito", 
                JOptionPane.INFORMATION_MESSAGE);
            
            this.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Error al actualizar usuario: " + e.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtClave = new javax.swing.JTextField();
        BtnEditar = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();
        LabelEditarUsuario = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        txtFechaNacimiento = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtTele = new javax.swing.JTextField();
        cmbRol = new javax.swing.JComboBox<>();
        cmbGenero = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(49, 82, 192));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Planifica+");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtId.setForeground(new java.awt.Color(153, 153, 153));
        txtId.setText("Name");
        txtId.setBorder(null);
        jPanel2.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 70, 234, 34));

        txtNombre.setForeground(new java.awt.Color(153, 153, 153));
        txtNombre.setText("contraseña");
        txtNombre.setBorder(null);
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 156, 234, 34));

        txtClave.setForeground(new java.awt.Color(153, 153, 153));
        txtClave.setText("correo");
        txtClave.setBorder(null);
        jPanel2.add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 110, 234, 34));

        BtnEditar.setBackground(new java.awt.Color(49, 82, 192));
        BtnEditar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnEditar.setForeground(new java.awt.Color(255, 255, 255));
        BtnEditar.setText("Editar");
        BtnEditar.setBorder(null);
        jPanel2.add(BtnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, 234, 34));

        BtnCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnCancelar.setForeground(new java.awt.Color(49, 82, 192));
        BtnCancelar.setText("Cancelar");
        BtnCancelar.setBorder(null);
        jPanel2.add(BtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 600, 234, 34));

        LabelEditarUsuario.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        LabelEditarUsuario.setForeground(new java.awt.Color(49, 82, 192));
        LabelEditarUsuario.setText("Editar Usuario");
        jPanel2.add(LabelEditarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        txtApellido.setForeground(new java.awt.Color(153, 153, 153));
        txtApellido.setText("telefono");
        txtApellido.setBorder(null);
        jPanel2.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 202, 234, 34));

        txtFechaNacimiento.setForeground(new java.awt.Color(153, 153, 153));
        txtFechaNacimiento.setText("telefono");
        txtFechaNacimiento.setBorder(null);
        jPanel2.add(txtFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 234, 34));

        txtDireccion.setForeground(new java.awt.Color(153, 153, 153));
        txtDireccion.setText("telefono");
        txtDireccion.setBorder(null);
        jPanel2.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 234, 34));

        txtCorreo.setForeground(new java.awt.Color(153, 153, 153));
        txtCorreo.setBorder(null);
        jPanel2.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 234, 34));

        txtTele.setForeground(new java.awt.Color(153, 153, 153));
        txtTele.setBorder(null);
        jPanel2.add(txtTele, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 234, 34));

        cmbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PACIENTE", "EMPLEADO", "MEDICO", "ADMIN" }));
        jPanel2.add(cmbRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 230, 30));

        cmbGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MASCULINO", "FEMENINO" }));
        jPanel2.add(cmbGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 502, 220, 30));

        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 300, -1));

        jScrollPane1.setViewportView(jPanel3);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 380, 430));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnEditar;
    private javax.swing.JLabel LabelEditarUsuario;
    private javax.swing.JComboBox<String> cmbGenero;
    private javax.swing.JComboBox<String> cmbRol;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtFechaNacimiento;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTele;
    // End of variables declaration//GEN-END:variables
}
