/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AgendarCitasAPP.view;


import AgendarCitasAPP.Dominio.Entidades.Paciente;
import AgendarCitasAPP.Dominio.Utils.JsonUtils;
import AgendarCitasAPP.Dominio.constantes.GeneroEnum;
import com.google.gson.reflect.TypeToken;
import java.io.IOException;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;


/**
 *
 * @author sebas
 */
public class EditarPacienteFrame extends javax.swing.JFrame {
    private Paciente pacienteOriginal;
    private Admin adminRef;
    
    

    public EditarPacienteFrame(Paciente paciente, Admin adminRef) {
        initComponents();
         
          this.pacienteOriginal = paciente;
        this.adminRef = adminRef;
        cargarDatosPaciente();
       
    }
    
      private void cargarDatosPaciente() {
        txtId.setText(pacienteOriginal.getId());
        txtNombre.setText(pacienteOriginal.getNombre());
        txtApellido.setText(pacienteOriginal.getApellido());
        txtCorreo.setText(pacienteOriginal.getCorreo());
        txtTele.setText(pacienteOriginal.getTelefono());
        txtClave.setText(pacienteOriginal.getClave());
        txtDireccion.setText(pacienteOriginal.getDireccion(txtDireccion.getText()));
        
        // Llenar y seleccionar el género
    cmbGenero.removeAllItems();
    for (GeneroEnum genero : GeneroEnum.values()) {
        cmbGenero.addItem(genero.getNombre());
    }
    cmbGenero.setSelectedItem(pacienteOriginal.getGenero());

    // Establecer la fecha de nacimiento
    if (pacienteOriginal.getFechaNacimiento() != null) {
        txtFechaNacimiento.setText(pacienteOriginal.getFechaNacimiento().toString());
    }

       

        
        
        
        // etc. para género, fecha, rol si aplica
    }

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {
    try {
        // Actualizar datos del objeto
        pacienteOriginal.setNombre(txtNombre.getText());
        pacienteOriginal.setApellido(txtApellido.getText());
        pacienteOriginal.setCorreo(txtCorreo.getText());
        pacienteOriginal.setTelefono(txtTele.getText());
        pacienteOriginal.setClave(txtClave.getText());
        pacienteOriginal.setDireccion(txtDireccion.getText());

        // Fecha de nacimiento
        try {
            LocalDate fecha = LocalDate.parse(txtFechaNacimiento.getText());
            pacienteOriginal.setFechaNacimiento(fecha);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Formato de fecha incorrecto. Usa yyyy-MM-dd");
            return;
        }

        // Género (guardado como String)
        String generoSeleccionado = cmbGenero.getSelectedItem().toString();
        pacienteOriginal.setGenero(generoSeleccionado);

        // Leer JSON, actualizar lista y guardar
        java.lang.reflect.Type tipoLista = new TypeToken<List<Paciente>>(){}.getType();
        List<Paciente> pacientes = JsonUtils.leerJson("pacientes.json", tipoLista);

        for (int i = 0; i < pacientes.size(); i++) {
            if (pacientes.get(i).getId().equals(pacienteOriginal.getId())) {
                pacientes.set(i, pacienteOriginal);
                break;
            }
        }

        JsonUtils.guardarJson("Pacientes.json", pacientes);

        JOptionPane.showMessageDialog(this, "Paciente actualizado.");
        adminRef.llenarTablaPacientes(pacientes);
        this.dispose();

    } catch (IOException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al guardar cambios.");
    }
    }

  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        LabelEditarUsuario = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtClave = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtFechaNacimiento = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtTele = new javax.swing.JTextField();
        cmbGenero = new javax.swing.JComboBox<>();
        btnGuardarPaciente = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(49, 82, 192));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Planifica+");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, -370, 300, -1));

        LabelEditarUsuario.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        LabelEditarUsuario.setForeground(new java.awt.Color(49, 82, 192));
        LabelEditarUsuario.setText("Editar Usuario");
        jPanel3.add(LabelEditarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        txtId.setEditable(false);
        txtId.setForeground(new java.awt.Color(153, 153, 153));
        txtId.setText("Id");
        txtId.setBorder(null);
        jPanel3.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 234, 34));

        txtClave.setForeground(new java.awt.Color(153, 153, 153));
        txtClave.setText("clave");
        txtClave.setBorder(null);
        jPanel3.add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 234, 34));

        txtNombre.setForeground(new java.awt.Color(153, 153, 153));
        txtNombre.setText("nombre");
        txtNombre.setBorder(null);
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel3.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 234, 34));

        txtApellido.setForeground(new java.awt.Color(153, 153, 153));
        txtApellido.setText("apellido");
        txtApellido.setBorder(null);
        jPanel3.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 234, 34));

        txtFechaNacimiento.setForeground(new java.awt.Color(153, 153, 153));
        txtFechaNacimiento.setText("fechanacimiento");
        txtFechaNacimiento.setBorder(null);
        jPanel3.add(txtFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 234, 34));

        txtDireccion.setForeground(new java.awt.Color(153, 153, 153));
        txtDireccion.setText("direccion");
        txtDireccion.setBorder(null);
        jPanel3.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 234, 34));

        txtCorreo.setForeground(new java.awt.Color(153, 153, 153));
        txtCorreo.setText("correo");
        txtCorreo.setBorder(null);
        jPanel3.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 234, 34));

        txtTele.setForeground(new java.awt.Color(153, 153, 153));
        txtTele.setText("telefono");
        txtTele.setBorder(null);
        jPanel3.add(txtTele, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 234, 34));

        cmbGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino", "Otros" }));
        jPanel3.add(cmbGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 230, 30));

        btnGuardarPaciente.setBackground(new java.awt.Color(49, 82, 192));
        btnGuardarPaciente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGuardarPaciente.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarPaciente.setText("Editar");
        btnGuardarPaciente.setBorder(null);
        btnGuardarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPacienteActionPerformed(evt);
            }
        });
        jPanel3.add(btnGuardarPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 234, 34));

        BtnCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnCancelar.setForeground(new java.awt.Color(49, 82, 192));
        BtnCancelar.setText("Cancelar");
        BtnCancelar.setBorder(null);
        jPanel3.add(BtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 234, 34));

        jScrollPane1.setViewportView(jPanel3);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 800, 430));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnGuardarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPacienteActionPerformed
   btnGuardarPaciente.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnGuardarActionPerformed(evt);
    }
});
    }//GEN-LAST:event_btnGuardarPacienteActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JLabel LabelEditarUsuario;
    private javax.swing.JButton btnGuardarPaciente;
    private javax.swing.JComboBox<String> cmbGenero;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtFechaNacimiento;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTele;
    // End of variables declaration//GEN-END:variables
}
