/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AgendarCitasAPP.view;

import AgendarCitasAPP.Dominio.Entidades.Medico;
import AgendarCitasAPP.Dominio.Utils.JsonUtils;
import AgendarCitasAPP.Dominio.constantes.GeneroEnum;
import AgendarCitasAPP.view.Admin;
import com.google.gson.reflect.TypeToken;
import java.io.IOException;
import java.util.List;
import javax.swing.JOptionPane;

    
public class EditarMedicoFrame extends javax.swing.JFrame {

    private Medico medicoOriginal;
    private Admin adminRef;
    
    public EditarMedicoFrame(Medico medico, Admin adminRef) {
        initComponents();
        
        
           btnGuardarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarMedicoActionPerformed(evt);
            }
        });

        this.medicoOriginal = medico;
        this.adminRef = adminRef;
        cargarDatosMedico();
    }
     private void cargarDatosMedico() {
        txtId.setText(medicoOriginal.getId());
        txtNombre.setText(medicoOriginal.getNombre());
        txtApellido.setText(medicoOriginal.getApellido());
        txtCorreo.setText(medicoOriginal.getCorreo());
        txtTele.setText(medicoOriginal.getTelefono());
        
        cmbGenero.removeAllItems();
    for (GeneroEnum genero : GeneroEnum.values()) {
        cmbGenero.addItem(genero.getNombre());
    }
    cmbGenero.setSelectedItem(medicoOriginal.getGenero());
        
        txtClave.setText(medicoOriginal.getClave());
        cmbEspecialidad.setSelectedItem(medicoOriginal.getEspecialidad());
        // ... completar con otros campos si tienes
        // También podrías llenar un combo de género, rol, etc., igual que en paciente
    }
      private void btnGuardarMedicoActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            // Actualizar datos del objeto medicoOriginal con los valores de los campos
            medicoOriginal.setNombre(txtNombre.getText());
            medicoOriginal.setApellido(txtApellido.getText());
            medicoOriginal.setCorreo(txtCorreo.getText());
            medicoOriginal.setTelefono(txtTele.getText());
            medicoOriginal.setClave(txtClave.getText());
            String generoSeleccionado = cmbGenero.getSelectedItem().toString();
            medicoOriginal.setGenero(generoSeleccionado);
            medicoOriginal.setEspecialidad(cmbEspecialidad.getSelectedItem().toString());
            // actualizar otros campos si tienes...

            // Leer lista de médicos desde JSON
            java.lang.reflect.Type tipoLista = new TypeToken<List<Medico>>(){}.getType();
            List<Medico> medicos = JsonUtils.leerJson("Medicos.json", tipoLista);

            // Buscar y reemplazar el médico editado
            for (int i = 0; i < medicos.size(); i++) {
                if (medicos.get(i).getId().equals(medicoOriginal.getId())) {
                    medicos.set(i, medicoOriginal);
                    break;
                }
            }

            // Guardar la lista actualizada
            JsonUtils.guardarJson("Medicos.json", medicos);

            JOptionPane.showMessageDialog(this, "Médico actualizado.");
            adminRef.llenarTablaMedicos(medicos);
            this.dispose();

        } catch (IOException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al guardar cambios.");
        }
    }

   

   
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtId = new javax.swing.JTextField();
        txtClave = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtTele = new javax.swing.JTextField();
        cmbGenero = new javax.swing.JComboBox<>();
        btnGuardarMedico = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();
        cmbEspecialidad = new javax.swing.JComboBox<>();
        LabelEditarUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(49, 82, 192));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Planifica+");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, -370, 300, -1));

        txtId.setEditable(false);
        txtId.setForeground(new java.awt.Color(153, 153, 153));
        txtId.setText("Id");
        txtId.setBorder(null);
        jPanel3.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 234, 34));

        txtClave.setForeground(new java.awt.Color(153, 153, 153));
        txtClave.setText("clave");
        txtClave.setBorder(null);
        jPanel3.add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 234, 34));

        txtNombre.setForeground(new java.awt.Color(153, 153, 153));
        txtNombre.setText("nombre");
        txtNombre.setBorder(null);
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel3.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 234, 34));

        txtApellido.setForeground(new java.awt.Color(153, 153, 153));
        txtApellido.setText("apellido");
        txtApellido.setBorder(null);
        jPanel3.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 234, 34));

        txtCorreo.setForeground(new java.awt.Color(153, 153, 153));
        txtCorreo.setText("correo");
        txtCorreo.setBorder(null);
        jPanel3.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 234, 34));

        txtTele.setForeground(new java.awt.Color(153, 153, 153));
        txtTele.setText("telefono");
        txtTele.setBorder(null);
        jPanel3.add(txtTele, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 234, 34));

        cmbGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MASCULINO", "FEMENINO" }));
        jPanel3.add(cmbGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 230, 30));

        btnGuardarMedico.setBackground(new java.awt.Color(49, 82, 192));
        btnGuardarMedico.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGuardarMedico.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarMedico.setText("Editar");
        btnGuardarMedico.setBorder(null);
        btnGuardarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarMedicoActionPerformed(evt);
            }
        });
        jPanel3.add(btnGuardarMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 234, 34));

        BtnCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnCancelar.setForeground(new java.awt.Color(49, 82, 192));
        BtnCancelar.setText("Cancelar");
        BtnCancelar.setBorder(null);
        jPanel3.add(BtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 234, 34));

        jPanel3.add(cmbEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 62, 230, 30));

        jScrollPane1.setViewportView(jPanel3);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 800, 430));

        LabelEditarUsuario.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        LabelEditarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        LabelEditarUsuario.setText("Editar Medico");
        jPanel1.add(LabelEditarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnEditarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarMedicoActionPerformed
      
    }//GEN-LAST:event_btnEditarMedicoActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JLabel LabelEditarUsuario;
    private javax.swing.JButton btnGuardarMedico;
    private javax.swing.JComboBox<String> cmbEspecialidad;
    private javax.swing.JComboBox<String> cmbGenero;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTele;
    // End of variables declaration//GEN-END:variables
}
