/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AgendarCitasAPP.view;

/**
 *
 * @author Sebastian JB
 */
public class EditarMedicoFrame extends javax.swing.JFrame {

    /**
     * Creates new form EditarMedicoFrame
     */
    public EditarMedicoFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        LabelEditarUsuario = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtClave = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtTele = new javax.swing.JTextField();
        cmbRol = new javax.swing.JComboBox<>();
        cmbGenero = new javax.swing.JComboBox<>();
        btnEditarMedico = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(49, 82, 192));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Planifica+");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, -370, 300, -1));

        LabelEditarUsuario.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        LabelEditarUsuario.setForeground(new java.awt.Color(49, 82, 192));
        LabelEditarUsuario.setText("Editar Medico");
        jPanel3.add(LabelEditarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        txtId.setEditable(false);
        txtId.setForeground(new java.awt.Color(153, 153, 153));
        txtId.setText("Id");
        txtId.setBorder(null);
        jPanel3.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 234, 34));

        txtClave.setForeground(new java.awt.Color(153, 153, 153));
        txtClave.setText("clave");
        txtClave.setBorder(null);
        jPanel3.add(txtClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 234, 34));

        txtNombre.setForeground(new java.awt.Color(153, 153, 153));
        txtNombre.setText("nombre");
        txtNombre.setBorder(null);
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel3.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 234, 34));

        txtApellido.setForeground(new java.awt.Color(153, 153, 153));
        txtApellido.setText("apellido");
        txtApellido.setBorder(null);
        jPanel3.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 234, 34));

        txtCorreo.setForeground(new java.awt.Color(153, 153, 153));
        txtCorreo.setText("correo");
        txtCorreo.setBorder(null);
        jPanel3.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, 234, 34));

        txtTele.setForeground(new java.awt.Color(153, 153, 153));
        txtTele.setText("telefono");
        txtTele.setBorder(null);
        jPanel3.add(txtTele, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 234, 34));

        cmbRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PACIENTE", "EMPLEADO", "MEDICO", "ADMIN" }));
        jPanel3.add(cmbRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 230, 30));

        cmbGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MASCULINO", "FEMENINO" }));
        jPanel3.add(cmbGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 230, 30));

        btnEditarMedico.setBackground(new java.awt.Color(49, 82, 192));
        btnEditarMedico.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEditarMedico.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarMedico.setText("Editar");
        btnEditarMedico.setBorder(null);
        btnEditarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarMedicoActionPerformed(evt);
            }
        });
        jPanel3.add(btnEditarMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, 234, 34));

        BtnCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnCancelar.setForeground(new java.awt.Color(49, 82, 192));
        BtnCancelar.setText("Cancelar");
        BtnCancelar.setBorder(null);
        jPanel3.add(BtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 234, 34));

        jScrollPane1.setViewportView(jPanel3);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 800, 430));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnEditarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarMedicoActionPerformed
     
    }//GEN-LAST:event_btnEditarMedicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarMedicoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarMedicoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarMedicoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarMedicoFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarMedicoFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JLabel LabelEditarUsuario;
    private javax.swing.JButton btnEditarMedico;
    private javax.swing.JComboBox<String> cmbGenero;
    private javax.swing.JComboBox<String> cmbRol;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTele;
    // End of variables declaration//GEN-END:variables
}
