/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package AgendarCitasAPP.view;

import AgendarCitasAPP.Controllers.SingUpController;
import javax.swing.*;

/**
 *
 * @author Sebastian JB
 */
public class register extends javax.swing.JFrame {

    /**
     * Creates new form register
     */
    public register() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        if (text_nameSingUp == null || text_correoSingUp == null || text_passSingUp == null || pfConfirmarClave == null ||
        text_cellSingUp == null || combo_genero == null || pfConfirmarClave == null || 
        btn_SingUp == null || btn_Login == null) {
    
    JOptionPane.showMessageDialog(this, 
        "Error: Componentes no inicializados\n" +
        "text_nameSingUp: " + (text_nameSingUp != null) + "\n" +
        "text_correoSingUp: " + (text_correoSingUp != null) + "\n" +
        "text_passSingUp: " + (text_passSingUp != null) + "\n" +
        "pfConfirmarClave: " + (pfConfirmarClave != null) + "\n" +
        "text_cellSingUp: " + (text_cellSingUp != null) + "\n" +
        "combo_genero: " + (combo_genero != null) + "\n" +
        "combo_rol: " + (combo_rol != null) + "\n" +
        //"tabPanePrincipal: " + (tabPanePrincipal != null) + "\n" +
        "btn_SingUp: " + (btn_SingUp != null) + "\n" +
        "btn_Login: " + (btn_Login != null),
        "Error", JOptionPane.ERROR_MESSAGE);
    return;
}

// Crear el controlador y conectar el botón al método registrar
    SingUpController controller = new SingUpController(
        text_nameSingUp, text_correoSingUp, text_passSingUp, pfConfirmarClave,
        text_cellSingUp, combo_genero, combo_rol, btn_SingUp, btn_Login
    );

    btn_SingUp.addActionListener(e -> controller.registrarUsuario());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        text_nameSingUp = new javax.swing.JTextField();
        text_correoSingUp = new javax.swing.JTextField();
        btn_SingUp = new javax.swing.JButton();
        btn_Login = new javax.swing.JButton();

        jLabel1 = new javax.swing.JLabel();
        text_cellSingUp = new javax.swing.JTextField();
        pfConfirmarClave = new javax.swing.JPasswordField();
        text_passSingUp = new javax.swing.JPasswordField();
        combo_genero = new javax.swing.JComboBox<>();
        combo_rol = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(49, 82, 192));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Planifica+");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(49, 82, 192));
        jLabel3.setText("Register to ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));


        text_nameSingUp.setForeground(new java.awt.Color(153, 153, 153));
        text_nameSingUp.setText("Name");
        text_nameSingUp.setBorder(null);
        jPanel2.add(text_nameSingUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 234, 34));


        text_correoSingUp.setForeground(new java.awt.Color(153, 153, 153));
        text_correoSingUp.setText("correo");
        text_correoSingUp.setBorder(null);
        jPanel2.add(text_correoSingUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 234, 34));

        btn_SingUp.setBackground(new java.awt.Color(49, 82, 192));
        btn_SingUp.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_SingUp.setForeground(new java.awt.Color(255, 255, 255));
        btn_SingUp.setText("Register");
        btn_SingUp.setBorder(null);
        btn_SingUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SingUpActionPerformed(evt);
            }
        });
        jPanel2.add(btn_SingUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 234, 34));

        btn_Login.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_Login.setForeground(new java.awt.Color(49, 82, 192));
        btn_Login.setText("Log in");
        btn_Login.setBorder(null);
        jPanel2.add(btn_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, 234, 34));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(49, 82, 192));
        jLabel1.setText("Planifica+");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        text_cellSingUp.setForeground(new java.awt.Color(153, 153, 153));
        text_cellSingUp.setText("telefono");
        text_cellSingUp.setBorder(null);
        jPanel2.add(text_cellSingUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 234, 34));

        pfConfirmarClave.setText("pfConfirmarClave");
        jPanel2.add(pfConfirmarClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 230, 30));

        text_passSingUp.setText("jPasswordField1");
        jPanel2.add(text_passSingUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 230, 30));

        combo_genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino", "Otros" }));
        jPanel2.add(combo_genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 230, 30));

        combo_rol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paciente", "Empleado", "Medico", "Admin", " " }));
        jPanel2.add(combo_rol, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 230, 30));

        jScrollPane1.setViewportView(jPanel2);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 340, 390));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//Inicio de funcion de boton sing up

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    private void btn_SingUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SingUpActionPerformed
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_SingUpActionPerformed



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Login;
    private javax.swing.JButton btn_SingUp;
    private javax.swing.JComboBox<String> combo_genero;
    private javax.swing.JComboBox<String> combo_rol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;

    private javax.swing.JPasswordField pfConfirmarClave;
    private javax.swing.JTextField text_cellSingUp;
    private javax.swing.JTextField text_correoSingUp;
    private javax.swing.JTextField text_nameSingUp;
    private javax.swing.JPasswordField text_passSingUp;

    // End of variables declaration//GEN-END:variables
}
